version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/on/host/mongodb_data
